# Auto-generated by update-mods. Do not edit.
{
  balm = {
    projectId = "MBAkmtvl";
    versionId = "x4SzggaK";
    version = "21.0.56+fabric-1.21.1";
    filename = "balm-fabric-1.21.1-21.0.56.jar";
    url = "https://cdn.modrinth.com/data/MBAkmtvl/versions/x4SzggaK/balm-fabric-1.21.1-21.0.56.jar";
    hash = "sha256-ko9x2QsAZLpFDjEhEnPIdJGvE/ggs8GZKyaBHgvSLTg=";
  };
  "cardinal-components-api" = {
    projectId = "K01OU20C";
    versionId = "nLsCe2VD";
    version = "6.1.3";
    filename = "cardinal-components-api-6.1.3.jar";
    url = "https://cdn.modrinth.com/data/K01OU20C/versions/nLsCe2VD/cardinal-components-api-6.1.3.jar";
    hash = "sha256-MCqKS8LjTL/69hr3WrXeR8Br+hWUNmZYcK5hCSsPaaI=";
  };
  "cloth-config" = {
    projectId = "9s6osm5g";
    versionId = "HpMb5wGb";
    version = "15.0.140+fabric";
    filename = "cloth-config-15.0.140-fabric.jar";
    url = "https://cdn.modrinth.com/data/9s6osm5g/versions/HpMb5wGb/cloth-config-15.0.140-fabric.jar";
    hash = "sha256-M4lOldo69ZAUs50SZYbVJB4H6jn4YYdj4w2rY3QF+V8=";
  };
  cobblemon = {
    projectId = "MdwFAVRL";
    versionId = "s64m1opn";
    version = "1.7.1";
    filename = "Cobblemon-fabric-1.7.1+1.21.1.jar";
    url = "https://cdn.modrinth.com/data/MdwFAVRL/versions/s64m1opn/Cobblemon-fabric-1.7.1%2B1.21.1.jar";
    hash = "sha256-+tv31oPyc+k8ZzymGV08HYqslpN6eoFRJMQ0qSH+cbE=";
  };
  "cobblemon-smartphone" = {
    projectId = "n2f1HbK8";
    versionId = "3zK00ysw";
    version = "1.0.5";
    filename = "cobblemon_smartphone-fabric-1.0.5.jar";
    url = "https://cdn.modrinth.com/data/n2f1HbK8/versions/3zK00ysw/cobblemon_smartphone-fabric-1.0.5.jar";
    hash = "sha256-0v9ikahO0EY2l/rC1NkGbYntMTO2OxOsOm6bEtf7vhU=";
  };
  "fabric-api" = {
    projectId = "P7dR8mSH";
    versionId = "m6zu1K31";
    version = "0.116.7+1.21.1";
    filename = "fabric-api-0.116.7+1.21.1.jar";
    url = "https://cdn.modrinth.com/data/P7dR8mSH/versions/m6zu1K31/fabric-api-0.116.7%2B1.21.1.jar";
    hash = "sha256-CAGMxIyXQVo4AWoA29Wix6Rgumt6BRaQqMs9u16EgqQ=";
  };
  "fabric-language-kotlin" = {
    projectId = "Ha28R6CL";
    versionId = "N6D3uiZF";
    version = "1.13.8+kotlin.2.3.0";
    filename = "fabric-language-kotlin-1.13.8+kotlin.2.3.0.jar";
    url = "https://cdn.modrinth.com/data/Ha28R6CL/versions/N6D3uiZF/fabric-language-kotlin-1.13.8%2Bkotlin.2.3.0.jar";
    hash = "sha256-dglT2NPR+jKjU1k9dE4pF9ipHKiSOulRi17yZ2pjEAI=";
  };
  "inventory-profiles-next" = {
    projectId = "O7RBXm3n";
    versionId = "A2gB9UGG";
    version = "fabric-1.21.1-2.2.3";
    filename = "InventoryProfilesNext-fabric-1.21.1-2.2.3.jar";
    url = "https://cdn.modrinth.com/data/O7RBXm3n/versions/A2gB9UGG/InventoryProfilesNext-fabric-1.21.1-2.2.3.jar";
    hash = "sha256-ZkUbLOkU6qSHMTLNchUwETsJlOV5VPsuzw/6Uxq0hHY=";
  };
  jei = {
    projectId = "u6dRKJwZ";
    versionId = "TvqzuFwN";
    version = "19.27.0.340";
    filename = "jei-1.21.1-fabric-19.27.0.340.jar";
    url = "https://cdn.modrinth.com/data/u6dRKJwZ/versions/TvqzuFwN/jei-1.21.1-fabric-19.27.0.340.jar";
    hash = "sha256-gMNb6eQvynHspXflODNpAlR8H+P1re2yt5VGqwH2a78=";
  };
  libipn = {
    projectId = "onSQdWhM";
    versionId = "3rPzmg5m";
    version = "fabric-1.21.1-6.6.2";
    filename = "libIPN-fabric-1.21.1-6.6.2.jar";
    url = "https://cdn.modrinth.com/data/onSQdWhM/versions/3rPzmg5m/libIPN-fabric-1.21.1-6.6.2.jar";
    hash = "sha256-SDOY1tkhJ1QIgsL2dqN++/2Y2hpR/fuGsXehj2B8KpY=";
  };
  trashslot = {
    projectId = "vRYk0bv7";
    versionId = "pc61Sh6M";
    version = "21.1.4+fabric-1.21.1";
    filename = "trashslot-fabric-1.21.1-21.1.4.jar";
    url = "https://cdn.modrinth.com/data/vRYk0bv7/versions/pc61Sh6M/trashslot-fabric-1.21.1-21.1.4.jar";
    hash = "sha256-Swa0dclp/XtJpzA1RDSItAHnG8q6E0Rw/etA01dWAN8=";
  };
  travelersbackpack = {
    projectId = "rlloIFEV";
    versionId = "9kIZO4k5";
    version = "1.21.1-10.1.31";
    filename = "travelersbackpack-fabric-1.21.1-10.1.31.jar";
    url = "https://cdn.modrinth.com/data/rlloIFEV/versions/9kIZO4k5/travelersbackpack-fabric-1.21.1-10.1.31.jar";
    hash = "sha256-ZugE6LSNhkFsfR9drwsJG+4BSucl69RVa3xmN0U/SbQ=";
  };
}
