#!/usr/bin/env bash

echo "Running nix fmt on staged files..."
staged_files=$(git diff --cached --name-only --diff-filter=d | grep '\.nix$' || true)

if [ -n "$staged_files" ]; then
    echo "$staged_files" | xargs nix fmt
    echo "$staged_files" | xargs git add
else
    echo "No staged .nix files to format."
fi